### ISSUE TITLE
Need some demo/examples

### ISSUE THREAD

**Issue by Sogl** [dersimn/grav-plugin-photoswipe#1]
Hello!

Can you provide some code examples how to use this plugin?

**Comment by dersimn** [comment]
After installing and activating the plugin you should be able to use images just like in [Featherlight](https://github.com/getgrav/grav-plugin-featherlight) (don't install both). You can activate the lightbox functionality for images in markdown by specifying:

```
![Sample Image](sample-image.jpg?lightbox=1&cropResize=200,200)
```

**Comment by Hendrik-Koehler** [comment]
Thanks dersimn!
the plugin is working fine, I just wonder how to enable/ disable the functionality on a page basis. 
In   photoswipe.php you mentioned:   * if enabled on this page, load the JS + CSS theme. *:
    public function onTwigSiteVariables()  { $config = $this->config->get('plugins.photoswipe'); ... 
Is this implemented to allow enable/ disable on a page-basis e.g. in the backend Grav UI?

However, if not, this can be done easily by my own via twig template editing and e.g. using page-specific user (front matter) variables to enable/disable the ressource loading. So no big deal.

**Comment by dersimn** [comment]
I'm using this plugin just for small RTFM websites, therefore I had no need to enable/disable it for single pages, but feel free to fork this project and implement it yourself.

You can also push it to the Grav "Appstore" or however they call it. I didn't even bother about that for my projects.

**Comment by dersimn** [comment]
Updated README, reopen if you have further questions
