### ISSUE TITLE
Use for gallery / grid

### ISSUE THREAD

**Issue by gymnae** [dersimn/grav-plugin-photoswipe#2]
Thanks for your plugin,
I saw http://www.timovolz.de/projekte which uses photoswipe, maybe this plugin even, in grav. I wondered how they are using photoswipe to greate a grid of thumbnails. They combine it with lazyloaded for a good effect.
Would anyone know how to use photoswipe for building such a grid?
Cheers

**Comment by dersimn** [comment]
That would be an issue for the Grav Support, I guess. This is just the plugin for displaying images in fullscreen, the CMS is responsible for grid arrays and stuff.

**Comment by gymnae** [comment]
@dersimn, thank you for your reply. Then I will try to look at templates and if I can find twig examples to achieve what I seek.

**Comment by gymnae** [comment]
A follow up to this "issue": I managed to generate a nice grid with the help of flexbin and the pictures are displayed using your plugin. But how to get them to display in a gallery fashion?
Featherlight offers the option to click through images in ´the lightbox like in a gallery with a global gallery toggle. Is there a way to do this here too? Photoswipe offers a gallery functionality according to its docs, but I'm not sure how to trigger it. For Featherlight triggering the gallery requires no change in the twig file or page content, just the setting for the plugin.
Currently I'm using the fork of @gimmixAT, his fork is closed for reporting issues.
