### ISSUE TITLE
Is it possible to add captions?

### ISSUE THREAD

**Issue by gymnae** [dersimn/grav-plugin-photoswipe#3]
I saw that featherlight added the option to add captions (https://github.com/getgrav/grav-plugin-featherlight/pull/11) and I wondered if your plugin also allows to add captions.
Right now, I cannot add a variable with the IPTC based caption to be used for the created thumbnail.

**Comment by dersimn** [comment]
`![Caption text](some_picture.png?lightbox&resize=200,200)`

Updated README, feel free to reopen if you have further questions on this
